version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env
#    ports:
#      - "5432:5432"
    deploy:
      placement:
        constraints:
          - "node.labels.type==db"

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
    env_file:
      - db.env
    depends_on:
      - db
    deploy:
      placement:
        constraints:
          - "node.labels.type==nextcloud"

  web:
    image: nginx:alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - nextcloud:/var/www/html:ro
    depends_on:
      - app
    deploy:
      placement:
        constraints:
          - "node.labels.type==nextcloud"

volumes:
  db:
    driver_opts:
      type: none
      o: bind
      device: /home/shved/120G/VOLUMES/db
  nextcloud:
    driver_opts:
      type: none
      o: bind
      device: /home/shved/Passport/VOLUMES/nextcloud
