version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env
    ports:
      - "5432:5432"

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
    env_file:
      - db.env
    depends_on:
      - db

  web:
    build: ./web
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html:ro
    depends_on:
      - app

volumes:
  db:
    driver_opts:
      type: none
      o: bind
      device: /home/shved/Passport/VOLUMES/db
  nextcloud:
    driver_opts:
      type: none
      o: bind
      device: /home/shved/Passport/VOLUMES/nextcloud
